version: '{build}'
image: Ubuntu1804
environment:
  global:
    HAXELIB_ROOT: /home/appveyor/haxelib
    HAXE_INSTALLDIR: /home/appveyor/haxe

install:
  - cd /home/appveyor
  - sudo add-apt-repository ppa:haxe/releases -y
  - sudo apt update
  - sudo apt install neko tar gcc g++ gcc-multilib g++-multilib -y
  - wget https://github.com/HaxeFoundation/haxe/releases/download/4.1.5/haxe-4.1.5-linux64.tar.gz
  - mkdir $HAXE_INSTALLDIR
  - tar -xf haxe-4.1.5-linux64.tar.gz -C $HAXE_INSTALLDIR
  - export PATH=$PATH:$HAXE_INSTALLDIR/haxe_20201231082044_5e33a78aa
  - mkdir $HAXELIB_ROOT && haxelib setup $HAXELIB_ROOT
  - haxelib install lime 7.9.0
  - haxelib install openfl 9.1.0
  - haxelib install flixel 4.11.0
  - haxelib install flixel-addons 2.11.0
  - haxelib install flixel-ui 2.3.3
  - haxelib install hscript 2.4.0
  - haxelib git faxe https://github.com/uhrobots/faxe.git
  - haxelib git polymod https://github.com/mcagabe19/polymod-for-kade1.5.git
  - haxelib git extension-webm https://github.com/KadeDev/extension-webm.git
  - haxelib run lime rebuild extension-webm linux
  - haxelib git linc_luajit https://github.com/sirox228/linc_luajit.git
  - haxelib install actuate 1.8.9
  - haxelib list
  - cd /home/appveyor/projects/kade-engine-linux

build_script:
  - haxelib run lime build linux

after_build:
  - tar -cvf KadeEngine-Linux.tar -C /home/appveyor/projects/kade-engine-linux/export/release/linux/bin .

artifacts:
- path: build-ubuntu18.04-64.tar
  name: build-ubuntu18.04-64.tar
