version: '{build}'
image: Ubuntu1804
environment:
  global:
    HAXELIB_ROOT: /home/appveyor/haxelib
    HAXE_INSTALLDIR: /home/appveyor/haxe

install:
  - cd /home/appveyor
  - sudo add-apt-repository ppa:haxe/releases -y
  - sudo apt update
  - sudo apt install neko tar gcc g++ gcc-multilib g++-multilib -y
  - wget https://github.com/HaxeFoundation/haxe/releases/download/4.1.5/haxe-4.1.5-linux64.tar.gz
  - mkdir $HAXE_INSTALLDIR
  - tar -xf haxe-4.1.5-linux64.tar.gz -C $HAXE_INSTALLDIR
  - export PATH=$PATH:$HAXE_INSTALLDIR/haxe_20201231082044_5e33a78aa
  - mkdir $HAXELIB_ROOT && haxelib setup $HAXELIB_ROOT
  - haxelib install hxcpp 4.2.1 --quiet
  - haxelib install lime 7.9.0 --quiet
  - haxelib install openfl 9.1.0 --quiet
  - haxelib install flixel 4.11.0 --quiet
  - haxelib install flixel-addons 2.11.0 --quiet
  - haxelib install flixel-ui 2.3.3 --quiet
  - haxelib install hscript 2.4.0 --quiet
  - haxelib git faxe https://github.com/uhrobots/faxe.git
  - haxelib git linc_luajit https://github.com/sirox228/linc_luajit.git
  - haxelib git polymod https://github.com/mcagabe19/polymod-for-kade1.5.git
  - haxelib install actuate 1.8.9 --quiet
  - clear
  - cd /home/appveyor/projects/kade-engine-linux

build_script:
  - haxelib run lime build linux -64
  - mv /home/appveyor/projects/kade-engine-linux/export/release/linux/bin /home/appveyor/projects/kade-engine-linux/export/release/linux/bin64
  - haxelib run lime build linux -32

after_build:
  - tar -cvf build-ubuntu18.04-64.tar -C /home/appveyor/projects/kade-engine-linux/export/release/linux/bin64 .
  - tar -cvf build-ubuntu18.04-32.tar -C /home/appveyor/projects/kade-engine-linux/export/release/linux/bin .

artifacts:
  - path: build-ubuntu18.04-32.tar
    name: Build Ubuntu18 32Bit

  - path: build-ubuntu18.04-64.tar
    name: Build Ubuntu18 64Bit
